# Generated by Django 4.1.3 on 2023-12-25 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="person",
            name="birth_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
